In [1]:
import numpy as np

In [3]:
n = 100
d = 25
k = 5

In [7]:
data = np.random.uniform(size=(n, d))

In [9]:
data.shape

(100, 25)

In [13]:
indices = np.random.choice(n, k, replace=False)

In [14]:
indices

array([67, 14, 79, 56, 28])

In [15]:
centers = data[indices]

In [17]:
centers.shape

(5, 25)

In [18]:
labels = np.empty(n)

In [20]:
labels.shape

(100,)

In [24]:
data[0]

array([0.81040127, 0.43658021, 0.8806107 , 0.98028988, 0.92649515,
       0.33879622, 0.71181562, 0.6969235 , 0.64575968, 0.67895559,
       0.53061782, 0.61579801, 0.35433662, 0.13102664, 0.3022433 ,
       0.30724441, 0.64751513, 0.61009386, 0.53966849, 0.80223414,
       0.15596885, 0.96071854, 0.18849735, 0.30900925, 0.82034375])

In [29]:
centers.shape

(5, 25)

In [31]:
np.argmin(np.sum((data[0] - centers) ** 2, axis=1))

4

In [32]:
data[:, None].shape

(100, 1, 25)

In [33]:
centers[None].shape

(1, 5, 25)

In [41]:
diff = data[:, None] - centers[None]

In [42]:
diff.shape

(100, 5, 25)

In [44]:
distances_squared = np.sum(diff ** 2, axis=2)

In [45]:
distances_squared.shape

(100, 5)

In [47]:
labels = np.argmin(distances_squared, axis=1)

In [48]:
labels.shape

(100,)

In [49]:
labels

array([4, 3, 2, 4, 4, 4, 0, 0, 3, 4, 4, 4, 3, 0, 1, 4, 0, 3, 4, 4, 0, 0,
       3, 3, 3, 0, 4, 0, 4, 0, 4, 0, 2, 0, 4, 4, 4, 4, 0, 4, 0, 2, 4, 0,
       4, 3, 4, 4, 0, 0, 4, 4, 0, 4, 4, 0, 3, 2, 4, 4, 3, 4, 0, 1, 0, 4,
       0, 0, 4, 4, 4, 0, 4, 0, 4, 4, 4, 1, 0, 2, 4, 4, 0, 4, 4, 0, 0, 0,
       1, 4, 4, 2, 0, 3, 4, 4, 0, 4, 0, 4], dtype=int64)

In [53]:
labels[:, None].shape

(100, 1)

In [54]:
centers.shape

(5, 25)

In [57]:
(labels[:, None] == range(k)).shape

(100, 5)

In [85]:
onehot_labels = labels[:, None] == np.arange(k, dtype=np.int32)

In [86]:
onehot_labels[:5] # compare with labels above

array([[False, False, False, False,  True],
       [False, False, False,  True, False],
       [False, False,  True, False, False],
       [False, False, False, False,  True],
       [False, False, False, False,  True]])

In [61]:
onehot_labels.shape

(100, 5)

In [63]:
b_data, b_oh = np.broadcast_arrays(data[:, None], onehot_labels[:, :, None]) # (n, k, d), (n, k, d)

In [64]:
b_data.shape, b_oh.shape

((100, 5, 25), (100, 5, 25))

In [75]:
b_data[:2, :, :10] # first 10 values of data sample only...

array([[[0.81040127, 0.43658021, 0.8806107 , 0.98028988, 0.92649515,
         0.33879622, 0.71181562, 0.6969235 , 0.64575968, 0.67895559],
        [0.81040127, 0.43658021, 0.8806107 , 0.98028988, 0.92649515,
         0.33879622, 0.71181562, 0.6969235 , 0.64575968, 0.67895559],
        [0.81040127, 0.43658021, 0.8806107 , 0.98028988, 0.92649515,
         0.33879622, 0.71181562, 0.6969235 , 0.64575968, 0.67895559],
        [0.81040127, 0.43658021, 0.8806107 , 0.98028988, 0.92649515,
         0.33879622, 0.71181562, 0.6969235 , 0.64575968, 0.67895559],
        [0.81040127, 0.43658021, 0.8806107 , 0.98028988, 0.92649515,
         0.33879622, 0.71181562, 0.6969235 , 0.64575968, 0.67895559]],

       [[0.56983538, 0.6579278 , 0.32102772, 0.9336031 , 0.49343154,
         0.25709433, 0.71299215, 0.14800904, 0.58813468, 0.67354685],
        [0.56983538, 0.6579278 , 0.32102772, 0.9336031 , 0.49343154,
         0.25709433, 0.71299215, 0.14800904, 0.58813468, 0.67354685],
        [0.56983538, 0.65

In [77]:
b_oh[:2, :, :5]

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [ True,  True,  True,  True,  True]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [ True,  True,  True,  True,  True],
        [False, False, False, False, False]]])

In [71]:
new_centers = b_data.mean(axis=0, where=b_oh)

In [72]:
new_centers.shape

(5, 25)

In [87]:
onehot_labels  = np.eye(k)[labels]

In [88]:
onehot_labels.shape

(100, 5)

In [89]:
onehot_labels[:5]

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]])

In [93]:
group_counts = np.bincount(labels, minlength=k)

In [95]:
group_counts[:, None].shape

(5, 1)

In [99]:
labels

array([4, 3, 2, 4, 4, 4, 0, 0, 3, 4, 4, 4, 3, 0, 1, 4, 0, 3, 4, 4, 0, 0,
       3, 3, 3, 0, 4, 0, 4, 0, 4, 0, 2, 0, 4, 4, 4, 4, 0, 4, 0, 2, 4, 0,
       4, 3, 4, 4, 0, 0, 4, 4, 0, 4, 4, 0, 3, 2, 4, 4, 3, 4, 0, 1, 0, 4,
       0, 0, 4, 4, 4, 0, 4, 0, 4, 4, 4, 1, 0, 2, 4, 4, 0, 4, 4, 0, 0, 0,
       1, 4, 4, 2, 0, 3, 4, 4, 0, 4, 0, 4], dtype=int64)

In [97]:
group_sums = np.apply_along_axis(lambda w:np.bincount(labels, weights=w), 0, data)

In [98]:
group_sums.shape

(5, 25)

In [100]:
group_sums

array([[20.67057042, 12.5832722 , 13.71464934, 14.29865791, 11.81822224,
        14.55816316, 16.36199105, 22.23354239, 13.08476444, 19.03712386,
        14.9542604 , 18.51569183, 15.21081324, 15.4882575 , 19.17897578,
        17.54314059, 17.24973173, 12.42280076, 18.42193423, 14.24156236,
        15.37699882, 13.05663125, 15.54781433, 12.36230732, 14.09705448],
       [ 1.15785692,  1.89578889,  2.80019038,  2.31645169,  3.11194667,
         0.86771838,  3.14287989,  0.90133927,  2.48285581,  3.20106529,
         1.38337371,  1.93186168,  0.49723546,  2.66333745,  1.10423224,
         1.34966317,  2.74090294,  2.77373784,  1.19899049,  0.80374474,
         1.82448145,  2.14209274,  1.2050333 ,  1.36761843,  1.94549393],
       [ 4.24310663,  3.92579007,  3.17224817,  4.40124366,  2.75696808,
         2.64935981,  2.95537922,  1.44021819,  3.47075796,  1.92779737,
         2.76885599,  3.12639613,  1.9859191 ,  2.88251871,  3.51342442,
         0.82228978,  1.16489129,  4.42374774,  4

In [103]:
new_centers2 = group_sums / group_counts[:, None]

In [104]:
np.all(new_centers == new_centers2)

True

In [105]:
np.all(centers == new_centers2)

False