In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [7]:
np.flip(a.T, axis=1)

array([[10,  5,  0],
       [11,  6,  1],
       [12,  7,  2],
       [13,  8,  3],
       [14,  9,  4]])

In [8]:
np.concatenate((a.T, np.flip(a.T, axis=1)), axis=1)

array([[ 0,  5, 10, 10,  5,  0],
       [ 1,  6, 11, 11,  6,  1],
       [ 2,  7, 12, 12,  7,  2],
       [ 3,  8, 13, 13,  8,  3],
       [ 4,  9, 14, 14,  9,  4]])

In [9]:
np.concatenate((a.T, np.flip(a.T, axis=1)), axis=0)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [10,  5,  0],
       [11,  6,  1],
       [12,  7,  2],
       [13,  8,  3],
       [14,  9,  4]])

In [10]:
np.sum(a, axis=0)

array([15, 18, 21, 24, 27])

In [11]:
np.sum(a, axis=0, keepdims=True)

array([[15, 18, 21, 24, 27]])

In [12]:
np.sum(a, axis=1)

array([10, 35, 60])

In [13]:
np.sum(a, axis=1, keepdims=True)

array([[10],
       [35],
       [60]])